spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=false

spring.datasource.url=${TRAVEL_STORY_DB_URL}

spring.jpa.hibernate.ddl-auto=validate

app.cors.allowed-origin-patterns=${TRAVEL_STORY_FRONTEND_URL}

server.forward-headers-strategy=framework